on: [push]
permissions:
  contents: read
jobs:
  build-chain:
    runs-on: ubuntu-latest
    steps:
      -
        id: build-chain
        uses: kiegroup/github-action-build-chain@v3
        with:
          definition-file: https://raw.githubusercontent.com/ikoznov-cross-repo/main/main/.github/definitions.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: actions/checkout@v3
        with:
          repository: ikoznov-cross-repo/lib1
          path: lib1
      -
        run: ls lib1
      -
        uses: actions/checkout@v3
        with:
          repository: ikoznov-cross-repo/main
          path: main
      -
        run: ls main
